name: Docker build and push
on:
  push:
    tags: [ "*.*.*" ]
jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set the value
        id: step_one
        run: |
            apt update && apt install -y jq
            export BUILD_VERSION=`jq .version package.json | sed 's/\"//g'`
            echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
      - name: Generate Docker tags
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            docker.io/vxcontrol/landing
          tags: |
            type=semver,pattern={{version}}
          flavor: |
            latest=true
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}