name: Docker build and push

on:
  push:
    tags:
        - '[0-9]+.[0-9]+.[0-9]+'
    branches: master

jobs:
  build_and_push_docker:
    name: Docker Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Docker tags
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            docker.io/vxcontrol/landing
          tags: |
            type=semver,pattern={{version}}
          flavor: |
            latest=true

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  reload_docker:
    runs-on: ubuntu-latest
    needs: build_and_push_docker
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      - name: Setup ssh
        run: |
         service ssh status
         eval `ssh-agent -s`
         mkdir -p /home/runner/.ssh/
         touch /home/runner/.ssh/id_rsa
         echo -e "${{secrets.SSH_PRIVATE_KEY}}" > /home/runner/.ssh/id_rsa
         chmod 700 /home/runner/.ssh/id_rsa

      - name: Add hostname
        run: |
          echo "${{ secrets.SSH_REMOTE_HOST }}" >> $GITHUB_WORKSPACE/ansible/ansible_hosts
      - name: Run playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook $GITHUB_WORKSPACE/ansible/deploy_playbook.yml -i $GITHUB_WORKSPACE/ansible/ansible_hosts
